config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :charities do
    resources :wishlists
  end

  resources :donors

  root "landing_page#index"

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout/:id',  to: 'sessions#destroy'
end

app/models/donor.rb
class Donor < ApplicationRecord
  belongs_to :user
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token
  skip_before_action :require_login, only: [:new, :create]

  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    if @donor.save
      render json: @donor
    end
    # respond_to do |format|
    #   if @donor.save
    #     format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
    #     format.json { render :show, status: :created, location: @donor }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @donor.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'Donor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit(:first_name, :last_name, :company_name, :user_id)
    end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_form.html.erb
<%= form_for(donor) do |f| %>
  <% if donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% donor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :company_name %>
    <%= f.text_field :company_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing Donor</h1>

<%= render 'form', donor: @donor %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Company name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donors.each do |donor| %>
      <tr>
        <td><%= donor.first_name %></td>
        <td><%= donor.last_name %></td>
        <td><%= donor.company_name %></td>
        <td><%= link_to 'Show', donor %></td>
        <td><%= link_to 'Edit', edit_donor_path(donor) %></td>
        <td><%= link_to 'Destroy', donor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donor', new_donor_path %>

app/views/donors/new.html.erb
<h1>New Donor</h1>

<%= render 'form', donor: @donor %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @donor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @donor.last_name %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @donor.company_name %>
</p>

<%= link_to 'Edit', edit_donor_path(@donor) %> |
<%= link_to 'Back', donors_path %>