config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :charities do
    resources :wishlists
  end

  resources :donors

  root "landing_page#index"

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout/:id',  to: 'sessions#destroy'
end

app/models/charity.rb
class Charity < ApplicationRecord
  # attr_accessible :logo
  belongs_to :user
  mount_uploader :logo, LogoUploader
  has_many :wishlists
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_action :set_charity, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token
  skip_before_action :require_login, only: [:new, :create, :index]


  # GET /charities
  # GET /charities.json
  def index
    @charities = Charity.all

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @charities }
    end
  end

  # GET /charities/1
  # GET /charities/1.json
  def show
    @charity = Charity.find_by(id: params[:id])
    @profile_editable = false
    if @charity.user_id == current_user.id
      @profile_editable = true
    end
    @donorview = false
    if current_user.donor.present?
      @donorview = true
    end
  end

  # GET /charities/new
  def new
    @charity = Charity.new
  end

  # GET /charities/1/edit
  def edit
  end

  def search



  end



  # POST /charities
  # POST /charities.json
  def create
    @charity = Charity.new(charity_params)

    if @charity.save
      render json: @charity
    end
    # respond_to do |format|
    #   if @charity.save
    #     # redirect_to root_path
    #     format.html { redirect_to @charity, notice: 'Charity was successfully created.' }
    #     format.json { render json: @charity, status: :created }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @charity.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /charities/1
  # PATCH/PUT /charities/1.json
  def update
    if current_user.charity.present? && current_user.charity.id == params[:id].to_i
      respond_to do |format|
        if @charity.update(charity_params)
          format.html { redirect_to @charity, notice: 'Charity was successfully updated.' }
          format.json { render :show, status: :ok, location: @charity }
        else
          format.html { render :edit }
          format.json { render json: @charity.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  # TODO better error handling here

  # DELETE /charities/1
  # DELETE /charities/1.json
  def destroy
    @charity.destroy
    respond_to do |format|
      format.html { redirect_to charities_url, notice: 'Charity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charity
      @charity = Charity.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charity_params
      params.require(:charity).permit(:charity_name, :cause, :description, :location, :logo, :charity_website, :shipping_address, :user_id)
    end
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/_form.html.erb
<%= form_for(charity) do |f| %>
  <% if charity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
      <% charity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :charity_name %>
    <%= f.text_field :charity_name %>
  </div>

  <div class="field">
    <%= f.label :cause %>
    <%= f.text_field :cause %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :logo %>
    <%= f.file_field :logo %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :shipping_address %>
    <%= f.text_area :shipping_address %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charities/edit.html.erb
<h1>Editing Charity</h1>

<%= render 'form', charity: @charity %>

<%= link_to 'Show', @charity %> |
<%= link_to 'Back', charities_path %>

app/views/charities/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container search_container">
  <div class="search_section1">
    <p class="search_blurb">Where would you like to make a difference?</p>
  </div>
  <div class="row dropdowns">
    <div class="col-md-4">
      <p id="error-message">Apologies, there aren't any charities matching that criteria.</p>
      <div class="dropdown search_dropdown">
        <button class="btn btn-primary dropdown-toggle" id="cause_search" type="button" data-toggle="dropdown">Charity Cause
        <span class="caret"></span></button>
        <ul class="cause_search dropdown-menu" id="cause_search_ul">
          <li>Animals</li>
          <li>Homeless</li>
          <li>Environmental</li>
          <li>Health</li>
          <li>Education</li>
          <li>International NGOs</li>
          <li>Arts & Culture</li>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <p id="error-message">Apologies, there aren't any charities matching that criteria.</p>
      <div class="dropdown search_dropdown">
        <button class="btn btn-primary dropdown-toggle" id="location_search" type="button" data-toggle="dropdown">Charity Locations
        <span class="caret"></span></button>
        <ul class="location_search dropdown-menu" id="location_search_ul">
          <li>Victoria</li>
          <li>South Australia</li>
          <li>Tasmania</li>
          <li>New South Wales</li>
          <li>Western Australia</li>
          <li>Queensland</li>
          <li>ACT</li>
          <li>Northern Territory</li>
          <li>International</li>
        </ul>
      </div>
    </div>
    <button class="charity_search_btn">Search</button>
  </div>
</div>

</div class="charities_results_container">
  <div><a class="results"></a></div>
  <div id="charities-results"></div>
</div>




<script src="/javascript/templates.js"></script>
<!-- <script src="/javascript/models/charity.js"></script>
<script src="/javascript/collections/charities.js"></script>
<script src="/javascript/views/ListView.js"></script>
<script src="/javascript/views/ListItemView.js"></script>
<script>
  var charities = new Charities();
  charities.reset(<%= raw(@charities.to_json) %>);
</script> -->
<!-- <script src="/javascript/charity_app.js"></script> -->
<!-- <%= link_to 'New Charity', new_charity_path %> -->

app/views/charities/new.html.erb
<h1>New Charity</h1>

<%= render 'form', charity: @charity %>

<%= link_to 'Back', charities_path %>

app/views/charities/show.html.erb
<%= stylesheet_link_tag 'charities' %>


<div class="container" id="profile"></div>

<div class="container">
    <div class="row">

        <div class="col-xs-3"></div>

        <div class="col-xs-6">
            <div class="form-horizontal wishlist-add" id="wishlist-add-table">

                <div class="form-group">
                    <input type="hidden" id="charity_id" value="<%= @charity.id %>"/>
                    <input type="text" class="form-control" id="item_name" placeholder="Item Name">
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" id="item_url" placeholder="Item URL">
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" id="estimated_price" placeholder="Est. Price"/>
                </div>

                <div class="form-group">
                    <button class="btn btn-primary btn-block" id="addwishlistbutton">Add Item!</button>
                </div>

            </div>
        </div>

    </div>
</div>

<div class="container">
  <div class="panel panel-default">
      <div class="panel-heading wishlist-heading">
          <h3 class="text-center panel-title">Our Wishlist</h3>
      </div>

      <div class="panel-body wishlist-panel-body">
          <div id="list-container"></div>
      </div>
  </div>
</div>

<div class="container">
  <div class="row">

      <div class="col-xs-3"></div>

        <div class="form-group">
          <div class="col-sm-6">
              <button class="btn btn-primary btn-block" id="removefromwishlistbutton">I've donated this!</button>
          </div>
        </div>
        
    </div>
</div>

<script src="/javascript/templates.js" charset="utf-8"></script>
<script src="/javascript/models/wish.js" charset="utf-8"></script>
<script src="/javascript/collections/wishes.js" charset="utf-8"></script>
<script src="/javascript/views/WishView.js" charset="utf-8"></script>
<script src="/javascript/views/WishItemView.js" charset="utf-8"></script>
<script src="/javascript/models/charityprofile.js"></script>
<script src="/javascript/views/CharityprofileView.js" charset="utf-8"></script>

<script>
    var charityprofile = new Charityprofile({id: <%= @charity.id %>})
    charityprofile.fetch();

    var wishes = new Wishes();
    wishes.reset(<%= raw(@charity.wishlists.to_json) %>);

    var profileEditable = <%= @profile_editable %>;
    var profileEditableString = profileEditable.toString();

    var donorView = <%= @donorview %>
</script>

<script src="/javascript/app.js" charset="utf-8"></script>