config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :charities do
    resources :wishlists
  end

  resources :donors

  root "landing_page#index"

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout/:id',  to: 'sessions#destroy'
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :charity
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  # GET /charities/:id/wishlists/new
  def new
    @charity = Charity.find(params[:charity_id])
    @wishlist = Wishlist.new
  end

  # GET /wishlists/1/edit
  def edit
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    if current_user.charity.present? && current_user.charity.id == wishlist_params["charity_id"].to_i
      @wishlist = Wishlist.new(wishlist_params)
        if @wishlist.save
          render json: @wishlist
        end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlist }
      else
        format.html { render :edit }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    if current_user.donor.present? || (current_user.charity.present? && current_user.charity.id == @wishlist.charity_id)
      @wishlist.destroy
      respond_to do |format|
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_params
      params.require(:wishlist).permit(:charity_id, :item_name, :item_url, :estimated_price, :estimated_price)
    end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wishlists</h1>

<table>
  <thead>
    <tr>
      <th>Charity</th>
      <th>Item name</th>
      <th>Item url</th>
      <th>Estimated price</th>
      <th>Estimated price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      <tr>
        <td><%= wishlist.charity %></td>
        <td><%= wishlist.item_name %></td>
        <td><%= wishlist.item_url %></td>
        <td><%= wishlist.estimated_price %></td>
        <td><%= wishlist.estimated_price %></td>
        <td><%= link_to 'Show', wishlist %></td>
        <td><%= link_to 'Edit', edit_wishlist_path(wishlist) %></td>
        <td><%= link_to 'Destroy', wishlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wishlist', new_wishlist_path %>

app/views/wishlists/new.html.erb
<h1>New Wishlist</h1>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Charity:</strong>
  <%= @wishlist.charity %>
</p>

<p>
  <strong>Item name:</strong>
  <%= @wishlist.item_name %>
</p>

<p>
  <strong>Item url:</strong>
  <%= @wishlist.item_url %>
</p>

<p>
  <strong>Estimated price:</strong>
  <%= @wishlist.estimated_price %>
</p>


<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>